/**
 * The homepage's editable copy.
 *
 * Every string is the text the designer wrote in the M.io Figma file
 * (key HWPX9rfWeQ8GPY1MnwF5jz, frame "homepage" 86:4671), transcribed rather
 * than rewritten.
 *
 * 86:4671 replaced the first homepage frame (3:4). It dropped the why-us,
 * add-ons, reviews and red closing-CTA sections, so their rows are gone from
 * here too; existing databases still hold them until the section is re-seeded
 * with `pnpm seed:home --section=home --force --prune`, which also brings the
 * reworded rows (hero headline, services headline, …) up to the new frame. The German, Arabic and Turkish columns are translations of that
 * English source, because the file only supplies one language for most of it.
 *
 * It lives in `content_blocks` rather than the message catalogue because this
 * is the text the business changes without a developer. Interface chrome —
 * button labels, validation messages, status names — stays in the catalogue,
 * where a missing key is a build failure rather than an empty heading.
 *
 * Seeded in all four locales so the dashboard's editor always has a row to
 * edit rather than an empty form.
 */

export interface ContentSeed {
  section: string;
  slot: string;
  kind: "text" | "textarea";
  label: string;
  sortOrder: number;
  values: { de: string; en: string; ar: string; tr: string };
}

export const HOME_CONTENT: ContentSeed[] = [
  // ── Hero ────────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "hero.tagline",
    kind: "text",
    label: "Hero — tagline (alt text of the wordmark above the headline)",
    sortOrder: 1,
    values: {
      de: "move on · Go on",
      en: "move on · Go on",
      ar: "move on · Go on",
      tr: "move on · Go on",
    },
  },
  {
    section: "home",
    slot: "hero.headline",
    kind: "text",
    label: "Hero — headline",
    sortOrder: 2,
    values: {
      de: "Umzug, Entrümpelung & Reinigung — einfach, fair und transparent.",
      en: "Moving, clearance & cleaning — made simple, fair and transparent.",
      ar: "النقل والإخلاء والتنظيف — ببساطة وإنصاف وشفافية.",
      tr: "Taşınma, boşaltma ve temizlik — basit, adil ve şeffaf.",
    },
  },
  {
    section: "home",
    slot: "hero.subline",
    kind: "textarea",
    label: "Hero — subline (a line break is kept)",
    sortOrder: 3,
    values: {
      de: "Move on. Go on.\nIhr Festpreisangebot in nur 2 Minuten — transparente Preise, keine versteckten Kosten und professioneller Service.",
      en: "Move on. Go on.\nGet your fixed-price quote in just 2 minutes — transparent pricing, no hidden costs, and professional service.",
      ar: "Move on. Go on.\nاحصل على عرض سعر ثابت خلال دقيقتين فقط — أسعار شفّافة، بلا تكاليف خفية، وخدمة احترافية.",
      tr: "Move on. Go on.\nSabit fiyat teklifinizi yalnızca 2 dakikada alın — şeffaf fiyatlar, gizli maliyet yok ve profesyonel hizmet.",
    },
  },
  {
    section: "home",
    slot: "hero.ctaPrimary",
    kind: "text",
    label: "Hero — primary button",
    sortOrder: 4,
    values: {
      de: "Jetzt Preis berechnen",
      en: "Calculate Price Now",
      ar: "احسب السعر الآن",
      tr: "Şimdi Fiyat Hesapla",
    },
  },
  {
    section: "home",
    slot: "hero.ctaSecondary",
    kind: "text",
    label: "Hero — secondary button",
    sortOrder: 5,
    values: {
      de: "Preise ansehen",
      en: "View Prices",
      ar: "اطّلع على الأسعار",
      tr: "Fiyatları Gör",
    },
  },
  {
    section: "home",
    slot: "hero.trust1",
    kind: "text",
    label: "Hero — trust point 1",
    sortOrder: 6,
    values: {
      de: "4,9/5 TÜV-zertifiziert",
      en: "4.9/5 TÜV Certified",
      ar: "4.9/5 معتمد من TÜV",
      tr: "4,9/5 TÜV Sertifikalı",
    },
  },
  {
    section: "home",
    slot: "hero.trust2",
    kind: "text",
    label: "Hero — trust point 2",
    sortOrder: 7,
    values: {
      de: "Haftpflichtversicherung inklusive",
      en: "Liability insurance included",
      ar: "تأمين المسؤولية مشمول",
      tr: "Sorumluluk sigortası dahil",
    },
  },

  // ── Services ────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "services.eyebrow",
    kind: "text",
    label: "Services — eyebrow",
    sortOrder: 8,
    values: {
      de: "Unsere Kernleistungen",
      en: "Our Core Services",
      ar: "خدماتنا الأساسية",
      tr: "Temel Hizmetlerimiz",
    },
  },
  {
    section: "home",
    slot: "services.headline",
    kind: "text",
    label: "Services — headline",
    sortOrder: 9,
    values: {
      de: "Leistungen",
      en: "Services",
      ar: "الخدمات",
      tr: "Hizmetler",
    },
  },
  {
    section: "home",
    slot: "services.subline",
    kind: "textarea",
    label: "Services — subline",
    sortOrder: 10,
    values: {
      de: "Kombinieren Sie Ihre Leistungen für maximale Ersparnis. Wir rechnen transparent nach Quadratmetern (m²) oder Einzelstücken ab.",
      en: "Combine your services for maximum savings. We calculate transparently by square meters (m²) or individual items.",
      ar: "ادمج خدماتك لتحقيق أقصى توفير. نحسب بشفافية بالمتر المربّع (م²) أو بالقطع المفردة.",
      tr: "En yüksek tasarruf için hizmetlerinizi birleştirin. Metrekare (m²) veya tek tek parça bazında şeffaf hesaplarız.",
    },
  },
  {
    section: "home",
    slot: "services.moving.title",
    kind: "text",
    label: "Service 1 — title",
    sortOrder: 11,
    values: {
      de: "1. Umzug & Transport",
      en: "1. Moving & Transport",
      ar: "1. النقل والترحيل",
      tr: "1. Taşınma ve Nakliye",
    },
  },
  {
    section: "home",
    slot: "services.moving.badge",
    kind: "text",
    label: "Service 1 — badge",
    sortOrder: 12,
    values: {
      de: "Beliebteste Wahl",
      en: "Most Popular Choice",
      ar: "الخيار الأكثر طلباً",
      tr: "En Popüler Seçim",
    },
  },
  {
    section: "home",
    slot: "services.moving.body",
    kind: "textarea",
    label: "Service 1 — body",
    sortOrder: 13,
    values: {
      de: "Stressfreie Privat-, Firmen- und Seniorenumzüge. Inklusive De- und Remontage.",
      en: "Stress-free residential, corporate, and senior moves. Includes disassembly and reassembly.",
      ar: "عمليات نقل سكنية وتجارية ولكبار السنّ بلا توتّر. تشمل الفكّ وإعادة التركيب.",
      tr: "Stressiz konut, kurumsal ve yaşlı taşımacılığı. Söküm ve yeniden montaj dahil.",
    },
  },
  {
    section: "home",
    slot: "services.moving.price",
    kind: "text",
    label: "Service 1 — price line",
    sortOrder: 14,
    values: {
      de: "Ab 29 €/m² oder nach Stückliste",
      en: "From €29/m² or by item list",
      ar: "ابتداءً من 29 €/م² أو حسب قائمة القطع",
      tr: "29 €/m² veya parça listesine göre",
    },
  },
  {
    section: "home",
    slot: "services.disposal.title",
    kind: "text",
    label: "Service 2 — title",
    sortOrder: 15,
    values: {
      de: "2. Entrümpelung & Entsorgung",
      en: "2. Clearance & Disposal",
      ar: "2. الإخلاء والتخلّص",
      tr: "2. Boşaltma ve Bertaraf",
    },
  },
  {
    section: "home",
    slot: "services.disposal.badge",
    kind: "text",
    label: "Service 2 — badge",
    sortOrder: 16,
    values: {
      de: "Express-Option",
      en: "Express Option",
      ar: "خيار سريع",
      tr: "Ekspres Seçenek",
    },
  },
  {
    section: "home",
    slot: "services.disposal.body",
    kind: "textarea",
    label: "Service 2 — body",
    sortOrder: 17,
    values: {
      de: "Professionelle und saubere Haushaltsauflösungen, Keller- und Dachbodenentrümpelung.",
      en: "Professional and spotless household clearances, cellar and attic cleanouts.",
      ar: "إخلاء منزلي احترافي ونظيف، وإفراغ الأقبية والعلّيات.",
      tr: "Profesyonel ve tertemiz ev boşaltma, bodrum ve çatı katı temizliği.",
    },
  },
  {
    section: "home",
    slot: "services.disposal.price",
    kind: "text",
    label: "Service 2 — price line",
    sortOrder: 18,
    values: {
      de: "Festpreisgarantie nach m²",
      en: "Fixed-price guarantee by m²",
      ar: "ضمان سعر ثابت حسب المتر المربّع",
      tr: "m² bazında sabit fiyat garantisi",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.title",
    kind: "text",
    label: "Service 3 — title",
    sortOrder: 19,
    values: {
      de: "3. Endreinigung & Übergabe",
      en: "3. Final Cleaning & Handover",
      ar: "3. التنظيف النهائي والتسليم",
      tr: "3. Son Temizlik ve Teslim",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.badge",
    kind: "text",
    label: "Service 3 — badge",
    sortOrder: 20,
    values: {
      de: "100 % Garantie",
      en: "100% Guarantee",
      ar: "ضمان 100%",
      tr: "%100 Garanti",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.body",
    kind: "textarea",
    label: "Service 3 — body",
    sortOrder: 21,
    values: {
      de: "Professionelle Reinigung mit Übergabegarantie gegenüber Ihrem Vermieter. Inklusive aller Reinigungsmittel.",
      en: "Professional cleaning with handover guarantee for your landlord. Includes all cleaning supplies.",
      ar: "تنظيف احترافي مع ضمان التسليم أمام المالك. يشمل جميع مواد التنظيف.",
      tr: "Ev sahibinize karşı teslim garantili profesyonel temizlik. Tüm temizlik malzemeleri dahil.",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.price",
    kind: "text",
    label: "Service 3 — price line",
    sortOrder: 22,
    values: {
      de: "Inklusive Übergabegarantie",
      en: "Includes handover guarantee",
      ar: "يشمل ضمان التسليم",
      tr: "Teslim garantisi dahil",
    },
  },
  {
    section: "home",
    slot: "services.packing.title",
    kind: "text",
    label: "Service 4 — title",
    sortOrder: 23,
    values: {
      de: "4. Ein- & Auspacken",
      en: "4. Packing & Unpacking",
      ar: "4. التغليف وفكّ التغليف",
      tr: "4. Paketleme ve Açma",
    },
  },
  {
    section: "home",
    slot: "services.packing.badge",
    kind: "text",
    label: "Service 4 — badge",
    sortOrder: 24,
    values: {
      de: "Maßgeschneidert",
      en: "Tailored Service",
      ar: "خدمة مصمّمة لك",
      tr: "Size Özel Hizmet",
    },
  },
  {
    section: "home",
    slot: "services.packing.body",
    kind: "textarea",
    label: "Service 4 — body",
    sortOrder: 25,
    values: {
      de: "Sorgfältiges Ein- und Auspacken mit hochwertigem Material zum Schutz Ihrer Wertsachen.",
      en: "Careful packing and unpacking with high-quality materials to protect your valuables.",
      ar: "تغليف وفكّ تغليف بعناية بمواد عالية الجودة لحماية مقتنياتك الثمينة.",
      tr: "Değerli eşyalarınızı korumak için yüksek kaliteli malzemelerle özenli paketleme ve açma.",
    },
  },
  {
    section: "home",
    slot: "services.packing.price",
    kind: "text",
    label: "Service 4 — price line",
    sortOrder: 26,
    values: {
      de: "Stundensatz oder Pauschalpreis",
      en: "Hourly rate or flat fee options",
      ar: "بسعر الساعة أو بسعر مقطوع",
      tr: "Saatlik ücret veya sabit fiyat seçenekleri",
    },
  },
  {
    section: "home",
    slot: "services.assembly.title",
    kind: "text",
    label: "Service 5 — title",
    sortOrder: 27,
    values: {
      de: "5. Möbelmontage",
      en: "5. Furniture Assembly",
      ar: "5. تركيب الأثاث",
      tr: "5. Mobilya Montajı",
    },
  },
  {
    section: "home",
    slot: "services.assembly.badge",
    kind: "text",
    label: "Service 5 — badge",
    sortOrder: 28,
    values: {
      de: "Erfahrene Monteure",
      en: "Expert Technicians",
      ar: "فنّيون خبراء",
      tr: "Uzman Teknisyenler",
    },
  },
  {
    section: "home",
    slot: "services.assembly.body",
    kind: "textarea",
    label: "Service 5 — body",
    sortOrder: 29,
    values: {
      de: "Effiziente Montage und Demontage aller Möbeltypen, auch von Sonderanfertigungen.",
      en: "Efficient assembly and disassembly of all furniture types, including custom pieces.",
      ar: "فكّ وتركيب فعّال لجميع أنواع الأثاث، بما في ذلك القطع المصنوعة حسب الطلب.",
      tr: "Özel yapım parçalar dahil her tür mobilyanın verimli montajı ve sökümü.",
    },
  },
  {
    section: "home",
    slot: "services.assembly.price",
    kind: "text",
    label: "Service 5 — price line",
    sortOrder: 30,
    values: {
      de: "Ab 15 € pro Stück",
      en: "From €15 per item",
      ar: "ابتداءً من 15 € للقطعة",
      tr: "Parça başı 15 €'dan başlayan fiyatlarla",
    },
  },
  {
    section: "home",
    slot: "services.storage.title",
    kind: "text",
    label: "Service 6 — title",
    sortOrder: 31,
    values: {
      de: "6. Einlagerung",
      en: "6. Storage Solutions",
      ar: "6. حلول التخزين",
      tr: "6. Depolama Çözümleri",
    },
  },
  {
    section: "home",
    slot: "services.storage.badge",
    kind: "text",
    label: "Service 6 — badge",
    sortOrder: 32,
    values: {
      de: "Sicher & flexibel",
      en: "Secure & Flexible",
      ar: "آمن ومرن",
      tr: "Güvenli ve Esnek",
    },
  },
  {
    section: "home",
    slot: "services.storage.body",
    kind: "textarea",
    label: "Service 6 — body",
    sortOrder: 33,
    values: {
      de: "Kurz- oder langfristige Einlagerung mit Klimatisierung und 24/7-Überwachung.",
      en: "Short or long-term storage options with climate control and 24/7 surveillance.",
      ar: "خيارات تخزين قصيرة أو طويلة الأمد مع تحكّم بالمناخ ومراقبة على مدار الساعة.",
      tr: "İklim kontrollü ve 7/24 gözetimli kısa veya uzun süreli depolama seçenekleri.",
    },
  },
  {
    section: "home",
    slot: "services.storage.price",
    kind: "text",
    label: "Service 6 — price line",
    sortOrder: 34,
    values: {
      de: "Ab 50 €/Monat",
      en: "Starting at €50/month",
      ar: "ابتداءً من 50 € شهرياً",
      tr: "Aylık 50 €'dan başlayan fiyatlarla",
    },
  },
  {
    section: "home",
    slot: "services.learnMore",
    kind: "text",
    label: "Service cards — link label",
    sortOrder: 35,
    values: { de: "Mehr erfahren", en: "Learn More", ar: "اعرف المزيد", tr: "Daha Fazla" },
  },

  // ── Values ──────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "values.eyebrow",
    kind: "text",
    label: "Values — eyebrow",
    sortOrder: 36,
    values: {
      de: "Unsere Werte",
      en: "Our Values",
      ar: "قيمنا",
      tr: "Değerlerimiz",
    },
  },
  {
    section: "home",
    slot: "values.headline",
    kind: "text",
    label: "Values — headline (**…** is brand red)",
    sortOrder: 37,
    values: {
      de: "Was macht uns zu **m.on**?",
      en: "What makes us **m.on**?",
      ar: "ما الذي يجعلنا **m.on**؟",
      tr: "Bizi **m.on** yapan ne?",
    },
  },
  {
    section: "home",
    slot: "values.imageAlt",
    kind: "text",
    label: "Values — photo description",
    sortOrder: 38,
    values: {
      de: "Zwei m.on-Umzugshelfer tragen Umzugskartons in eine helle Wohnung",
      en: "Two m.on movers carrying moving boxes into a bright flat",
      ar: "عاملا نقل من m.on يحملان صناديق النقل إلى شقة مضيئة",
      tr: "İki m.on taşıma görevlisi aydınlık bir daireye taşıma kolileri taşıyor",
    },
  },
  {
    section: "home",
    slot: "values.reviewsFigure",
    kind: "text",
    label: "Values — photo chip figure",
    sortOrder: 39,
    values: {
      de: "4.500+",
      en: "4,500+",
      ar: "4,500+",
      tr: "4.500+",
    },
  },
  {
    section: "home",
    slot: "values.reviewsLabel",
    kind: "text",
    label: "Values — photo chip label",
    sortOrder: 40,
    values: {
      de: "Fünf-Sterne-Bewertungen",
      en: "Five-Star Reviews",
      ar: "تقييم بخمس نجوم",
      tr: "Beş Yıldızlı Yorum",
    },
  },
  {
    section: "home",
    slot: "values.acronymLabel",
    kind: "text",
    label: "Values — acronym label",
    sortOrder: 41,
    values: {
      de: "Version A — Das Akronym",
      en: "Version A — The Acronym",
      ar: "النسخة أ — الاختصار",
      tr: "Versiyon A — Kısaltma",
    },
  },
  {
    section: "home",
    slot: "values.a1.letter",
    kind: "text",
    label: "Values — acronym letter 1",
    sortOrder: 42,
    values: {
      de: "M",
      en: "M",
      ar: "M",
      tr: "M",
    },
  },
  {
    section: "home",
    slot: "values.a1.word",
    kind: "text",
    label: "Values — acronym word 1",
    sortOrder: 43,
    values: {
      de: "Minutiös",
      en: "Meticulous",
      ar: "دقيق",
      tr: "Mükemmeliyetçi",
    },
  },
  {
    section: "home",
    slot: "values.a2.letter",
    kind: "text",
    label: "Values — acronym letter 2",
    sortOrder: 44,
    values: {
      de: "O",
      en: "O",
      ar: "O",
      tr: "O",
    },
  },
  {
    section: "home",
    slot: "values.a2.word",
    kind: "text",
    label: "Values — acronym word 2",
    sortOrder: 45,
    values: {
      de: "Ohnegleichen",
      en: "Outstanding",
      ar: "متميّز",
      tr: "Olağanüstü",
    },
  },
  {
    section: "home",
    slot: "values.a3.letter",
    kind: "text",
    label: "Values — acronym letter 3",
    sortOrder: 46,
    values: {
      de: "N",
      en: "N",
      ar: "N",
      tr: "N",
    },
  },
  {
    section: "home",
    slot: "values.a3.word",
    kind: "text",
    label: "Values — acronym word 3",
    sortOrder: 47,
    values: {
      de: "Nimmermüde",
      en: "Nimble",
      ar: "رشيق",
      tr: "Nitelikli",
    },
  },
  {
    section: "home",
    slot: "values.creedLabel",
    kind: "text",
    label: "Values — creed label",
    sortOrder: 48,
    values: {
      de: "Version B — Unser Credo",
      en: "Version B — The Creed",
      ar: "النسخة ب — مبادئنا",
      tr: "Versiyon B — İlkelerimiz",
    },
  },
  {
    section: "home",
    slot: "values.creed",
    kind: "text",
    label: "Values — creed words (comma separated)",
    sortOrder: 49,
    values: {
      de: "Ehrlich, Uniformiert, Freundlich, Kompetent, Service",
      en: "Honest, Uniformed, Nice, Knowledgeable, Service",
      ar: "صادق، بزيّ موحّد، لطيف، خبير، خدمة",
      tr: "Dürüst, Üniformalı, Nazik, Bilgili, Hizmet",
    },
  },
  {
    section: "home",
    slot: "values.body",
    kind: "textarea",
    label: "Values — body",
    sortOrder: 50,
    values: {
      de: "Unser Team aus zugelassenen und geschulten Fachkräften hat die meisten Fünf-Sterne-Bewertungen der Branche erhalten. Höflich, sorgsam mit Ihrem Hab und Gut und mit dem Anspruch, jeden Schritt zu einem wirklich angenehmen Erlebnis zu machen.",
      en: "Our team of licensed and trained professionals has earned the most five-star reviews in the industry. Courteous, careful with your belongings, and committed to making every step of the experience genuinely pleasant.",
      ar: "حصل فريقنا من المحترفين المرخَّصين والمدرَّبين على أكبر عدد من تقييمات الخمس نجوم في القطاع. لطفاء، حريصون على مقتنياتك، وملتزمون بأن تكون كل خطوة من التجربة ممتعة حقاً.",
      tr: "Lisanslı ve eğitimli profesyonellerden oluşan ekibimiz sektördeki en çok beş yıldızlı yorumu aldı. Nazik, eşyalarınıza özenli ve deneyimin her adımını gerçekten keyifli kılmaya kararlı.",
    },
  },
  {
    section: "home",
    slot: "values.cta",
    kind: "text",
    label: "Values — button",
    sortOrder: 51,
    values: {
      de: "Kostenloses Angebot erhalten",
      en: "Get Your Free Quote",
      ar: "احصل على عرضك المجاني",
      tr: "Ücretsiz Teklifinizi Alın",
    },
  },

  // ── Promise ─────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "promise.eyebrow",
    kind: "text",
    label: "Promise — eyebrow",
    sortOrder: 52,
    values: {
      de: "Unser Versprechen",
      en: "Our Promise",
      ar: "وعدنا",
      tr: "Sözümüz",
    },
  },
  {
    section: "home",
    slot: "promise.headline",
    kind: "text",
    label: "Promise — headline",
    sortOrder: 53,
    values: {
      de: "Wir nehmen Ihnen die Last von den Schultern",
      en: "We take the weight off your shoulders",
      ar: "نحمل عنك العبء",
      tr: "Yükü omuzlarınızdan alıyoruz",
    },
  },
  {
    section: "home",
    slot: "promise.body",
    kind: "textarea",
    label: "Promise — body",
    sortOrder: 54,
    values: {
      de: "Komplettpakete, Einzeltransporte, Verpacken und Entladen — dazu Verpackungsmaterial, damit Sie von Anfang bis Ende versorgt sind.",
      en: "Comprehensive packages, item transport, packing and unloading — plus packing materials available so you are covered from start to finish.",
      ar: "باقات شاملة ونقل القطع والتغليف والتفريغ — مع توفّر مواد التغليف لتكون مطمئناً من البداية إلى النهاية.",
      tr: "Kapsamlı paketler, eşya taşıma, paketleme ve boşaltma — ayrıca baştan sona hazır olmanız için paketleme malzemesi.",
    },
  },
  {
    section: "home",
    slot: "promise.cta",
    kind: "text",
    label: "Promise — button",
    sortOrder: 55,
    values: {
      de: "Unsere Leistungen entdecken",
      en: "Explore Our Services",
      ar: "اكتشف خدماتنا",
      tr: "Hizmetlerimizi Keşfedin",
    },
  },
  {
    section: "home",
    slot: "promise.imageAlt",
    kind: "text",
    label: "Promise — photo description",
    sortOrder: 56,
    values: {
      de: "Blick in einen Umzugswagen: in Decken gehüllte Möbel und gestapelte Kartons, für den Transport gesichert",
      en: "Inside a moving truck: furniture wrapped in blankets and stacked boxes, strapped for transport",
      ar: "داخل شاحنة نقل: أثاث ملفوف بالبطانيات وصناديق مكدّسة ومثبّتة للنقل",
      tr: "Taşıma kamyonunun içi: battaniyeye sarılmış mobilyalar ve nakliye için sabitlenmiş koliler",
    },
  },

  // ── Experience ──────────────────────────────────────────────────────
  {
    section: "home",
    slot: "experience.headline",
    kind: "text",
    label: "Experience — headline",
    sortOrder: 57,
    values: {
      de: "Einblicke in das m.on-Erlebnis",
      en: "Inside the m.on experience",
      ar: "من داخل تجربة m.on",
      tr: "m.on deneyiminin içinden",
    },
  },
  {
    section: "home",
    slot: "experience.subline",
    kind: "text",
    label: "Experience — subline",
    sortOrder: 58,
    values: {
      de: "Ein Einblick in die Sorgfalt, die wir jeden Tag in jedes Zuhause bringen.",
      en: "A glimpse into the daily standard of care we bring to every home.",
      ar: "لمحة عن مستوى العناية اليومي الذي نقدّمه لكل منزل.",
      tr: "Her eve taşıdığımız günlük özen standardına bir bakış.",
    },
  },
  {
    section: "home",
    slot: "experience.team.title",
    kind: "text",
    label: "Experience photo 1 — title",
    sortOrder: 59,
    values: {
      de: "Das Team",
      en: "The Team",
      ar: "الفريق",
      tr: "Ekip",
    },
  },
  {
    section: "home",
    slot: "experience.team.body",
    kind: "textarea",
    label: "Experience photo 1 — caption",
    sortOrder: 60,
    values: {
      de: "Festangestellte, geschulte und vollständig überprüfte Umzugsprofis.",
      en: "Employed, trained, and fully background-checked moving experts.",
      ar: "خبراء نقل موظَّفون ومدرَّبون وخضعوا لتدقيق كامل في خلفياتهم.",
      tr: "Kadrolu, eğitimli ve geçmişi tamamen kontrol edilmiş taşıma uzmanları.",
    },
  },
  {
    section: "home",
    slot: "experience.team.alt",
    kind: "text",
    label: "Experience photo 1 — description",
    sortOrder: 61,
    values: {
      de: "Die m.on-Umzugscrew in Uniform vor einem Umzugswagen",
      en: "The m.on moving crew in uniform in front of a moving truck",
      ar: "طاقم النقل من m.on بالزيّ الموحّد أمام شاحنة نقل",
      tr: "Üniformalı m.on taşıma ekibi bir taşıma kamyonunun önünde",
    },
  },
  {
    section: "home",
    slot: "experience.work.title",
    kind: "text",
    label: "Experience photo 2 — title",
    sortOrder: 62,
    values: {
      de: "Die Arbeit",
      en: "The Work",
      ar: "العمل",
      tr: "İş",
    },
  },
  {
    section: "home",
    slot: "experience.work.body",
    kind: "textarea",
    label: "Experience photo 2 — caption",
    sortOrder: 63,
    values: {
      de: "Präzise Verpackungsmethoden, die selbst Ihre wertvollsten Erbstücke schützen.",
      en: "Precise packing methods designed to protect your finest heirlooms.",
      ar: "أساليب تغليف دقيقة مصمَّمة لحماية أثمن مقتنياتك الموروثة.",
      tr: "En değerli yadigârlarınızı korumak için tasarlanmış hassas paketleme yöntemleri.",
    },
  },
  {
    section: "home",
    slot: "experience.work.alt",
    kind: "text",
    label: "Experience photo 2 — description",
    sortOrder: 64,
    values: {
      de: "Hände verschließen einen Umzugskarton mit Klebeband",
      en: "Hands sealing a moving box with packing tape",
      ar: "يدان تُغلقان صندوق نقل بشريط لاصق",
      tr: "Bir taşıma kolisini bantla kapatan eller",
    },
  },
  {
    section: "home",
    slot: "experience.result.title",
    kind: "text",
    label: "Experience photo 3 — title",
    sortOrder: 65,
    values: {
      de: "Das Ergebnis",
      en: "The Result",
      ar: "النتيجة",
      tr: "Sonuç",
    },
  },
  {
    section: "home",
    slot: "experience.result.body",
    kind: "textarea",
    label: "Experience photo 3 — caption",
    sortOrder: 66,
    values: {
      de: "Kommen Sie ohne Stress und mit einem guten Gefühl in Ihrem neuen Zuhause an.",
      en: "Arrive at your new address with zero stress and complete peace of mind.",
      ar: "اصل إلى عنوانك الجديد بلا أي توتّر وبراحة بال تامّة.",
      tr: "Yeni adresinize sıfır stresle ve tam bir iç huzuruyla varın.",
    },
  },
  {
    section: "home",
    slot: "experience.result.alt",
    kind: "text",
    label: "Experience photo 3 — description",
    sortOrder: 67,
    values: {
      de: "Eine Frau entspannt auf dem Sofa in ihrem frisch eingerichteten Wohnzimmer",
      en: "A woman relaxing on the sofa in her newly furnished living room",
      ar: "امرأة تسترخي على الأريكة في غرفة معيشتها المفروشة حديثاً",
      tr: "Yeni döşenmiş oturma odasında kanepede dinlenen bir kadın",
    },
  },

  // ── How it works ────────────────────────────────────────────────────
  {
    section: "home",
    slot: "how.eyebrow",
    kind: "text",
    label: "How it works — eyebrow",
    sortOrder: 68,
    values: {
      de: "In 3 einfachen Schritten",
      en: "In 3 Easy Steps",
      ar: "في 3 خطوات بسيطة",
      tr: "3 Kolay Adımda",
    },
  },
  {
    section: "home",
    slot: "how.headline",
    kind: "text",
    label: "How it works — headline",
    sortOrder: 69,
    values: {
      de: "So funktioniert es",
      en: "How It Works",
      ar: "كيف يعمل",
      tr: "Nasıl Çalışır",
    },
  },
  {
    section: "home",
    slot: "how.subline",
    kind: "textarea",
    label: "How it works — subline",
    sortOrder: 70,
    values: {
      de: "Unser vollständig digitaler Ablauf spart Ihnen Zeit, Telefonate und lästigen Papierkram.",
      en: "Our fully digital process saves you time, phone calls, and tedious paperwork.",
      ar: "عمليتنا الرقمية بالكامل توفّر عليك الوقت والمكالمات والأوراق المزعجة.",
      tr: "Tamamen dijital sürecimiz size zaman, telefon görüşmesi ve angarya evrak işi kazandırır.",
    },
  },
  {
    section: "home",
    slot: "how.step1.title",
    kind: "text",
    label: "Step 1 — title",
    sortOrder: 71,
    values: {
      de: "Kostenloses Angebot",
      en: "Free Quote",
      ar: "عرض سعر مجاني",
      tr: "Ücretsiz Teklif",
    },
  },
  {
    section: "home",
    slot: "how.step1.body",
    kind: "textarea",
    label: "Step 1 — body",
    sortOrder: 72,
    values: {
      de: "Nutzen Sie unseren m²-Rechner für ein unverbindliches Angebot in Echtzeit.",
      en: "Use our m² calculator for a non-binding offer in real time.",
      ar: "استخدم حاسبة المتر المربّع للحصول على عرض غير مُلزم فوراً.",
      tr: "Gerçek zamanlı, bağlayıcı olmayan teklif için m² hesaplayıcımızı kullanın.",
    },
  },
  {
    section: "home",
    slot: "how.step2.title",
    kind: "text",
    label: "Step 2 — title",
    sortOrder: 73,
    values: {
      de: "Termin buchen",
      en: "Book a Date",
      ar: "احجز موعداً",
      tr: "Tarih Seçin",
    },
  },
  {
    section: "home",
    slot: "how.step2.body",
    kind: "textarea",
    label: "Step 2 — body",
    sortOrder: 74,
    values: {
      de: "Sichern Sie sich Ihren Wunschtermin bequem online oder mit unserem Berater.",
      en: "Secure your preferred date easily online or with our advisor.",
      ar: "احجز موعدك المفضّل بسهولة عبر الإنترنت أو مع مستشارنا.",
      tr: "Tercih ettiğiniz tarihi çevrimiçi ya da danışmanımızla kolayca ayırtın.",
    },
  },
  {
    section: "home",
    slot: "how.step3.title",
    kind: "text",
    label: "Step 3 — title",
    sortOrder: 75,
    values: {
      de: "Umzug & Übergabe",
      en: "Move & Delivery",
      ar: "النقل والتسليم",
      tr: "Taşınma ve Teslim",
    },
  },
  {
    section: "home",
    slot: "how.step3.body",
    kind: "textarea",
    label: "Step 3 — body",
    sortOrder: 76,
    values: {
      de: "Unser Premium-Team erledigt den Rest — pünktlich, sauber und absolut professionell.",
      en: "Our premium team takes care of the rest — punctually, cleanly, and absolutely professionally.",
      ar: "فريقنا المتميّز يتولّى الباقي — في موعده وبنظافة واحتراف تام.",
      tr: "Premium ekibimiz gerisini halleder — dakik, temiz ve son derece profesyonel biçimde.",
    },
  },
  {
    section: "home",
    slot: "how.cta",
    kind: "text",
    label: "How it works — button",
    sortOrder: 77,
    values: {
      de: "Kostenloses Angebot erhalten",
      en: "Get Your Free Quote",
      ar: "احصل على عرضك المجاني",
      tr: "Ücretsiz Teklifinizi Alın",
    },
  },

  // ── Coverage ────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "areas.eyebrow",
    kind: "text",
    label: "Coverage — eyebrow",
    sortOrder: 78,
    values: { de: "Einsatzgebiet", en: "Coverage", ar: "نطاق الخدمة", tr: "Hizmet Alanı" },
  },
  {
    section: "home",
    slot: "areas.headline",
    kind: "text",
    label: "Coverage — headline",
    sortOrder: 79,
    values: {
      de: "Wo wir tätig sind",
      en: "Where We Operate",
      ar: "أين نعمل",
      tr: "Nerelerde Hizmet Veriyoruz",
    },
  },
  {
    section: "home",
    slot: "areas.subline",
    kind: "textarea",
    label: "Coverage — subline",
    sortOrder: 80,
    values: {
      de: "Wir bieten Umzugs- und Reinigungsleistungen in allen großen Metropolregionen an.",
      en: "We offer moving and cleaning services in all major metropolitan regions.",
      ar: "نقدّم خدمات النقل والتنظيف في جميع المناطق الحضرية الكبرى.",
      tr: "Tüm büyük metropol bölgelerinde taşıma ve temizlik hizmeti sunuyoruz.",
    },
  },
  {
    section: "home",
    slot: "areas.cities",
    kind: "textarea",
    label: "Coverage — city list (comma separated; the first is highlighted)",
    sortOrder: 81,
    values: {
      de: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg",
      en: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg",
      ar: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg",
      tr: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg",
    },
  },
  {
    section: "home",
    slot: "areas.districtsLabel",
    kind: "text",
    label: "Coverage — districts label",
    sortOrder: 82,
    values: {
      de: "Auch in Hamburg im Einsatz:",
      en: "Also serving in Hamburg:",
      ar: "نخدم أيضاً في هامبورغ:",
      tr: "Hamburg'da ayrıca hizmet verdiğimiz yerler:",
    },
  },
  {
    section: "home",
    slot: "areas.districts",
    kind: "text",
    label: "Coverage — districts (comma separated)",
    sortOrder: 83,
    values: {
      de: "Wandsbek, Altona",
      en: "Wandsbek, Altona",
      ar: "Wandsbek, Altona",
      tr: "Wandsbek, Altona",
    },
  },
  {
    section: "home",
    slot: "areas.trustFigure",
    kind: "text",
    label: "Coverage — chip figure",
    sortOrder: 84,
    values: {
      de: "100 %",
      en: "100%",
      ar: "100%",
      tr: "%100",
    },
  },
  {
    section: "home",
    slot: "areas.trustLabel",
    kind: "text",
    label: "Coverage — chip label",
    sortOrder: 85,
    values: {
      de: "Betrieb in Deutschland",
      en: "German Operations",
      ar: "عمليات في ألمانيا",
      tr: "Almanya'da Faaliyet",
    },
  },
  {
    section: "home",
    slot: "areas.mapAlt",
    kind: "text",
    label: "Coverage — map description",
    sortOrder: 86,
    values: {
      de: "Karte unseres Einsatzgebiets",
      en: "Map of our service area",
      ar: "خريطة نطاق خدمتنا",
      tr: "Hizmet bölgemizin haritası",
    },
  },

  // ── FAQ ─────────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "faq.eyebrow",
    kind: "text",
    label: "FAQ — eyebrow",
    sortOrder: 87,
    values: {
      de: "Support",
      en: "Support",
      ar: "الدعم",
      tr: "Destek",
    },
  },
  {
    section: "home",
    slot: "faq.headline",
    kind: "text",
    label: "FAQ — headline",
    sortOrder: 88,
    values: {
      de: "Häufig gestellte Fragen",
      en: "Frequently Asked Questions",
      ar: "الأسئلة الأكثر شيوعاً",
      tr: "Sık Sorulan Sorular",
    },
  },
  {
    section: "home",
    slot: "faq.subline",
    kind: "textarea",
    label: "FAQ — subline",
    sortOrder: 89,
    values: {
      de: "Alles Wichtige zu Abrechnung, Versicherung und unseren Abläufen.",
      en: "Everything you need to know about billing, insurance, and our processes.",
      ar: "كل ما تحتاج معرفته عن الفوترة والتأمين وإجراءاتنا.",
      tr: "Faturalandırma, sigorta ve süreçlerimiz hakkında bilmeniz gereken her şey.",
    },
  },
  {
    section: "home",
    slot: "faq.all",
    kind: "text",
    label: "FAQ — “all topics” tab",
    sortOrder: 90,
    values: {
      de: "Alle",
      en: "All",
      ar: "الكل",
      tr: "Tümü",
    },
  },
  {
    section: "home",
    slot: "faq.tag1",
    kind: "text",
    label: "FAQ — topic of question 1",
    sortOrder: 91,
    values: {
      de: "Versicherung",
      en: "Insurance",
      ar: "التأمين",
      tr: "Sigorta",
    },
  },
  {
    section: "home",
    slot: "faq.tag2",
    kind: "text",
    label: "FAQ — topic of question 2",
    sortOrder: 92,
    values: {
      de: "Abrechnung",
      en: "Billing",
      ar: "الفوترة",
      tr: "Faturalandırma",
    },
  },
  {
    section: "home",
    slot: "faq.tag3",
    kind: "text",
    label: "FAQ — topic of question 3",
    sortOrder: 93,
    values: {
      de: "Buchung",
      en: "Booking",
      ar: "الحجز",
      tr: "Rezervasyon",
    },
  },
  {
    section: "home",
    slot: "faq.tag4",
    kind: "text",
    label: "FAQ — topic of question 4",
    sortOrder: 94,
    values: {
      de: "Reinigung",
      en: "Cleaning",
      ar: "التنظيف",
      tr: "Temizlik",
    },
  },
  {
    section: "home",
    slot: "faq.moreTitle",
    kind: "text",
    label: "FAQ — closing line",
    sortOrder: 95,
    values: {
      de: "Nicht gefunden, wonach Sie suchen?",
      en: "Can't find what you're looking for?",
      ar: "لم تجد ما تبحث عنه؟",
      tr: "Aradığınızı bulamadınız mı?",
    },
  },
  {
    section: "home",
    slot: "faq.contact",
    kind: "text",
    label: "FAQ — contact button",
    sortOrder: 96,
    values: {
      de: "Kontakt aufnehmen",
      en: "Contact us",
      ar: "تواصل معنا",
      tr: "Bize ulaşın",
    },
  },

  // ── Footer ──────────────────────────────────────────────────────────
  {
    section: "footer",
    slot: "tagline",
    kind: "textarea",
    label: "Footer — tagline",
    sortOrder: 1,
    values: {
      de: "Ihr digitaler Partner für Umzug, Reinigung und Entrümpelung in ganz Deutschland. Schnell, transparent und zuverlässig.",
      en: "Your digital partner for moving, cleaning, and clearance across Germany. Fast, transparent, and reliable.",
      ar: "شريكك الرقمي للنقل والتنظيف والإخلاء في جميع أنحاء ألمانيا. سريع وشفّاف وموثوق.",
      tr: "Almanya genelinde taşınma, temizlik ve boşaltma için dijital ortağınız. Hızlı, şeffaf ve güvenilir.",
    },
  },
  {
    section: "footer",
    slot: "address",
    kind: "textarea",
    label: "Footer — address",
    sortOrder: 2,
    values: {
      de: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      en: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      ar: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      tr: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
    },
  },
  {
    section: "footer",
    slot: "rights",
    kind: "text",
    label: "Footer — rights",
    sortOrder: 3,
    values: {
      de: "Alle Rechte vorbehalten.",
      en: "All rights reserved.",
      ar: "جميع الحقوق محفوظة.",
      tr: "Tüm hakları saklıdır.",
    },
  },

  // ── Footer ──────────────────────────────────────────────────────────
  {
    section: "footer",
    slot: "brand",
    kind: "text",
    label: "Footer — legal name",
    sortOrder: 0,
    values: {
      de: "m.on GmbH",
      en: "m.on GmbH",
      ar: "m.on GmbH",
      tr: "m.on GmbH",
    },
  },
  {
    section: "footer",
    slot: "servicesTitle",
    kind: "text",
    label: "Footer — services column heading",
    sortOrder: 10,
    values: { de: "Leistungen", en: "Services", ar: "الخدمات", tr: "Hizmetler" },
  },
  {
    section: "footer",
    slot: "link.residential",
    kind: "text",
    label: "Footer link — residential move",
    sortOrder: 11,
    values: { de: "Privatumzug", en: "Residential Move", ar: "نقل سكني", tr: "Konut Taşıma" },
  },
  {
    section: "footer",
    slot: "link.corporate",
    kind: "text",
    label: "Footer link — corporate move",
    sortOrder: 12,
    values: { de: "Firmenumzug", en: "Corporate Move", ar: "نقل الشركات", tr: "Kurumsal Taşıma" },
  },
  {
    section: "footer",
    slot: "link.clearance",
    kind: "text",
    label: "Footer link — clearance",
    sortOrder: 13,
    values: {
      de: "Haushaltsauflösung",
      en: "Household Clearance",
      ar: "إخلاء المنازل",
      tr: "Ev Boşaltma",
    },
  },
  {
    section: "footer",
    slot: "link.senior",
    kind: "text",
    label: "Footer link — senior move",
    sortOrder: 14,
    values: { de: "Seniorenumzug", en: "Senior Move", ar: "نقل كبار السن", tr: "Yaşlı Taşıma" },
  },
  {
    section: "footer",
    slot: "link.cleaning",
    kind: "text",
    label: "Footer link — final cleaning",
    sortOrder: 15,
    values: { de: "Endreinigung", en: "Final Cleaning", ar: "التنظيف النهائي", tr: "Son Temizlik" },
  },
  {
    section: "footer",
    slot: "link.storage",
    kind: "text",
    label: "Footer link — storage",
    sortOrder: 16,
    values: { de: "Möbeleinlagerung", en: "Furniture Storage", ar: "تخزين الأثاث", tr: "Mobilya Depolama" },
  },
  {
    section: "footer",
    slot: "contactTitle",
    kind: "text",
    label: "Footer — contact column heading",
    sortOrder: 20,
    values: {
      de: "Kontakt & Support",
      en: "Contact & Support",
      ar: "الاتصال والدعم",
      tr: "İletişim ve Destek",
    },
  },
  {
    section: "footer",
    slot: "phone",
    kind: "text",
    label: "Footer — phone",
    sortOrder: 21,
    values: {
      de: "0800 123 456 78",
      en: "0800 123 456 78",
      ar: "0800 123 456 78",
      tr: "0800 123 456 78",
    },
  },
  {
    section: "footer",
    slot: "email",
    kind: "text",
    label: "Footer — email",
    sortOrder: 22,
    values: {
      de: "support@moveongo.de",
      en: "support@moveongo.de",
      ar: "support@moveongo.de",
      tr: "support@moveongo.de",
    },
  },
  {
    section: "footer",
    slot: "legal.imprint",
    kind: "text",
    label: "Footer legal — imprint",
    sortOrder: 30,
    values: { de: "Impressum", en: "Imprint", ar: "بيانات الناشر", tr: "Künye" },
  },
  {
    section: "footer",
    slot: "legal.privacy",
    kind: "text",
    label: "Footer legal — privacy",
    sortOrder: 31,
    // "Privacy" in the new footer (101:176); the old one said "Privacy Policy".
    values: { de: "Datenschutz", en: "Privacy", ar: "الخصوصية", tr: "Gizlilik" },
  },
  {
    section: "footer",
    slot: "legal.terms",
    kind: "text",
    label: "Footer legal — terms",
    sortOrder: 32,
    values: { de: "AGB", en: "Terms", ar: "الشروط والأحكام", tr: "Şartlar" },
  },
  {
    section: "footer",
    slot: "legal.cookies",
    kind: "text",
    label: "Footer legal — cookies",
    sortOrder: 33,
    values: { de: "Cookie-Richtlinie", en: "Cookie Policy", ar: "سياسة الكوكيز", tr: "Çerez Politikası" },
  },
  {
    section: "footer",
    slot: "social.instagram",
    kind: "text",
    label: "Footer social — Instagram URL",
    sortOrder: 40,
    values: {
      de: "https://instagram.com/mon",
      en: "https://instagram.com/mon",
      ar: "https://instagram.com/mon",
      tr: "https://instagram.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.x",
    kind: "text",
    label: "Footer social — X URL",
    sortOrder: 41,
    values: {
      de: "https://x.com/mon",
      en: "https://x.com/mon",
      ar: "https://x.com/mon",
      tr: "https://x.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.facebook",
    kind: "text",
    label: "Footer social — Facebook URL",
    sortOrder: 42,
    values: {
      de: "https://facebook.com/mon",
      en: "https://facebook.com/mon",
      ar: "https://facebook.com/mon",
      tr: "https://facebook.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.youtube",
    kind: "text",
    label: "Footer social — YouTube URL",
    sortOrder: 43,
    values: {
      de: "https://youtube.com/@mon",
      en: "https://youtube.com/@mon",
      ar: "https://youtube.com/@mon",
      tr: "https://youtube.com/@mon",
    },
  },
  /**
   * The new footer (101:168) shows Instagram, X and LinkedIn — LinkedIn had no
   * row. Same placeholder pattern as the others until the real profile exists.
   * Facebook and YouTube above are no longer drawn.
   */
  {
    section: "footer",
    slot: "social.linkedin",
    kind: "text",
    label: "Footer social — LinkedIn URL",
    sortOrder: 44,
    values: {
      de: "https://linkedin.com/company/mon",
      en: "https://linkedin.com/company/mon",
      ar: "https://linkedin.com/company/mon",
      tr: "https://linkedin.com/company/mon",
    },
  },
];
