/**
 * The homepage's editable copy.
 *
 * Every string is the text the designer wrote in the M.io Figma file
 * (key HWPX9rfWeQ8GPY1MnwF5jz, frame "homepage"), transcribed rather than
 * rewritten. The German, Arabic and Turkish columns are translations of that
 * English source, because the file only supplies one language for most of it.
 *
 * It lives in `content_blocks` rather than the message catalogue because this
 * is the text the business changes without a developer. Interface chrome —
 * button labels, validation messages, status names — stays in the catalogue,
 * where a missing key is a build failure rather than an empty heading.
 *
 * Seeded in all four locales so the dashboard's editor always has a row to
 * edit rather than an empty form.
 */

export interface ContentSeed {
  section: string;
  slot: string;
  /** "image" holds a picture's path or https URL, the same in every locale. */
  kind: "text" | "textarea" | "image";
  label: string;
  sortOrder: number;
  values: { de: string; en: string; ar: string; tr: string };
}

export const HOME_CONTENT: ContentSeed[] = [
  // ── Hero ────────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "hero.badge",
    kind: "text",
    label: "Hero — badge",
    sortOrder: 1,
    values: {
      de: "Rechner 100 % kostenlos & ohne Registrierung",
      en: "Calculator 100% free & no registration required",
      ar: "الحاسبة مجانية 100% وبدون تسجيل",
      tr: "Hesaplayıcı %100 ücretsiz, kayıt gerekmez",
    },
  },
  {
    section: "home",
    slot: "hero.headline",
    kind: "text",
    label: "Hero — headline",
    sortOrder: 2,
    values: {
      de: "Umzug, Entrümpelung & Reinigung — **fair, transparent, sofort berechnet**",
      en: "Moving, clearance & cleaning — **fair, transparent, instantly calculated**",
      ar: "نقل وإخلاء وتنظيف — **بإنصاف وشفافية وحساب فوري**",
      tr: "Taşınma, boşaltma ve temizlik — **adil, şeffaf, anında hesaplanır**",
    },
  },
  {
    section: "home",
    slot: "hero.subline",
    kind: "textarea",
    label: "Hero — subline",
    sortOrder: 3,
    values: {
      de: "Erhalten Sie Ihr Festpreisangebot in nur 2 Minuten. Berechnet nach m² oder Stückzahl. Keine versteckten Kosten, deutsche Fachkräfte, vollständig versichert.",
      en: "Get your fixed-price offer in just 2 minutes. Calculated by m² or item count. No hidden costs, German professionals, fully insured.",
      ar: "احصل على عرض السعر الثابت خلال دقيقتين فقط. يُحسب بالمتر المربّع أو بعدد القطع. بدون تكاليف خفية، فنّيون ألمان، وتأمين كامل.",
      tr: "Sabit fiyat teklifinizi yalnızca 2 dakikada alın. m² veya parça sayısına göre hesaplanır. Gizli maliyet yok, Alman profesyoneller, tam sigortalı.",
    },
  },
  {
    section: "home",
    slot: "hero.ctaPrimary",
    kind: "text",
    label: "Hero — primary button",
    sortOrder: 4,
    values: {
      de: "Jetzt Preis berechnen",
      en: "Calculate Price Now",
      ar: "احسب السعر الآن",
      tr: "Şimdi Fiyat Hesapla",
    },
  },
  {
    section: "home",
    slot: "hero.ctaSecondary",
    kind: "text",
    label: "Hero — secondary button",
    sortOrder: 5,
    values: {
      de: "Preise ansehen",
      en: "View Prices",
      ar: "اطّلع على الأسعار",
      tr: "Fiyatları Gör",
    },
  },
  {
    section: "home",
    slot: "hero.trust1",
    kind: "text",
    label: "Hero — trust point 1",
    sortOrder: 6,
    values: {
      de: "4,9/5 TÜV-zertifiziert",
      en: "4.9/5 TÜV Certified",
      ar: "4.9/5 معتمد من TÜV",
      tr: "4,9/5 TÜV Sertifikalı",
    },
  },
  {
    section: "home",
    slot: "hero.trust2",
    kind: "text",
    label: "Hero — trust point 2",
    sortOrder: 7,
    values: {
      de: "Haftpflichtversicherung inklusive",
      en: "Liability insurance included",
      ar: "تأمين المسؤولية مشمول",
      tr: "Sorumluluk sigortası dahil",
    },
  },

  // ── Services ────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "services.eyebrow",
    kind: "text",
    label: "Services — eyebrow",
    sortOrder: 10,
    values: {
      de: "Unsere Kernleistungen",
      en: "Our Core Services",
      ar: "خدماتنا الأساسية",
      tr: "Temel Hizmetlerimiz",
    },
  },
  {
    section: "home",
    slot: "services.headline",
    kind: "text",
    label: "Services — headline",
    sortOrder: 11,
    values: {
      de: "Drei Leistungen von einem Anbieter",
      en: "Three services from one provider",
      ar: "ثلاث خدمات من مزوّد واحد",
      tr: "Tek sağlayıcıdan üç hizmet",
    },
  },
  {
    section: "home",
    slot: "services.subline",
    kind: "textarea",
    label: "Services — subline",
    sortOrder: 12,
    values: {
      de: "Kombinieren Sie Ihre Leistungen für maximale Ersparnis. Wir rechnen transparent nach Quadratmetern (m²) oder Einzelstücken ab.",
      en: "Combine your services for maximum savings. We calculate transparently by square meters (m²) or individual items.",
      ar: "ادمج خدماتك لتحقيق أقصى توفير. نحسب بشفافية بالمتر المربّع (م²) أو بالقطع المفردة.",
      tr: "En yüksek tasarruf için hizmetlerinizi birleştirin. Metrekare (m²) veya tek tek parça bazında şeffaf hesaplarız.",
    },
  },

  {
    section: "home",
    slot: "services.moving.title",
    kind: "text",
    label: "Service 1 — title",
    sortOrder: 13,
    values: {
      de: "1. Umzug & Transport",
      en: "1. Moving & Transport",
      ar: "1. النقل والترحيل",
      tr: "1. Taşınma ve Nakliye",
    },
  },
  {
    section: "home",
    slot: "services.moving.badge",
    kind: "text",
    label: "Service 1 — badge",
    sortOrder: 14,
    values: {
      de: "Beliebteste Wahl",
      en: "Most Popular Choice",
      ar: "الخيار الأكثر طلباً",
      tr: "En Popüler Seçim",
    },
  },
  {
    section: "home",
    slot: "services.moving.body",
    kind: "textarea",
    label: "Service 1 — body",
    sortOrder: 15,
    values: {
      de: "Stressfreie Privat-, Firmen- und Seniorenumzüge. Inklusive De- und Remontage.",
      en: "Stress-free residential, corporate, and senior moves. Includes disassembly and reassembly.",
      ar: "عمليات نقل سكنية وتجارية ولكبار السنّ بلا توتّر. تشمل الفكّ وإعادة التركيب.",
      tr: "Stressiz konut, kurumsal ve yaşlı taşımacılığı. Söküm ve yeniden montaj dahil.",
    },
  },
  {
    section: "home",
    slot: "services.moving.price",
    kind: "text",
    label: "Service 1 — price line",
    sortOrder: 16,
    values: {
      de: "Ab 29 €/m² oder nach Stückliste",
      en: "From €29/m² or by item list",
      ar: "ابتداءً من 29 €/م² أو حسب قائمة القطع",
      tr: "29 €/m² veya parça listesine göre",
    },
  },

  {
    section: "home",
    slot: "services.disposal.title",
    kind: "text",
    label: "Service 2 — title",
    sortOrder: 17,
    values: {
      de: "2. Entrümpelung & Entsorgung",
      en: "2. Clearance & Disposal",
      ar: "2. الإخلاء والتخلّص",
      tr: "2. Boşaltma ve Bertaraf",
    },
  },
  {
    section: "home",
    slot: "services.disposal.badge",
    kind: "text",
    label: "Service 2 — badge",
    sortOrder: 18,
    values: {
      de: "Express-Option",
      en: "Express Option",
      ar: "خيار سريع",
      tr: "Ekspres Seçenek",
    },
  },
  {
    section: "home",
    slot: "services.disposal.body",
    kind: "textarea",
    label: "Service 2 — body",
    sortOrder: 19,
    values: {
      de: "Professionelle und saubere Haushaltsauflösungen, Keller- und Dachbodenentrümpelung.",
      en: "Professional and spotless household clearances, cellar and attic cleanouts.",
      ar: "إخلاء منزلي احترافي ونظيف، وإفراغ الأقبية والعلّيات.",
      tr: "Profesyonel ve tertemiz ev boşaltma, bodrum ve çatı katı temizliği.",
    },
  },
  {
    section: "home",
    slot: "services.disposal.price",
    kind: "text",
    label: "Service 2 — price line",
    sortOrder: 20,
    values: {
      de: "Festpreisgarantie nach m²",
      en: "Fixed-price guarantee by m²",
      ar: "ضمان سعر ثابت حسب المتر المربّع",
      tr: "m² bazında sabit fiyat garantisi",
    },
  },

  {
    section: "home",
    slot: "services.cleaning.title",
    kind: "text",
    label: "Service 3 — title",
    sortOrder: 21,
    values: {
      de: "3. Endreinigung & Übergabe",
      en: "3. Final Cleaning & Handover",
      ar: "3. التنظيف النهائي والتسليم",
      tr: "3. Son Temizlik ve Teslim",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.badge",
    kind: "text",
    label: "Service 3 — badge",
    sortOrder: 22,
    values: {
      de: "100 % Garantie",
      en: "100% Guarantee",
      ar: "ضمان 100%",
      tr: "%100 Garanti",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.body",
    kind: "textarea",
    label: "Service 3 — body",
    sortOrder: 23,
    values: {
      de: "Professionelle Reinigung mit Übergabegarantie gegenüber Ihrem Vermieter. Inklusive aller Reinigungsmittel.",
      en: "Professional cleaning with handover guarantee for your landlord. Includes all cleaning supplies.",
      ar: "تنظيف احترافي مع ضمان التسليم أمام المالك. يشمل جميع مواد التنظيف.",
      tr: "Ev sahibinize karşı teslim garantili profesyonel temizlik. Tüm temizlik malzemeleri dahil.",
    },
  },
  {
    section: "home",
    slot: "services.cleaning.price",
    kind: "text",
    label: "Service 3 — price line",
    sortOrder: 24,
    values: {
      de: "Inklusive Übergabegarantie",
      en: "Includes handover guarantee",
      ar: "يشمل ضمان التسليم",
      tr: "Teslim garantisi dahil",
    },
  },

  // ── Why us ──────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "why.eyebrow",
    kind: "text",
    label: "Why us — eyebrow",
    sortOrder: 30,
    values: {
      de: "Ihre Vorteile",
      en: "Your Benefits",
      ar: "مزاياك",
      tr: "Avantajlarınız",
    },
  },
  {
    section: "home",
    slot: "why.headline",
    kind: "text",
    label: "Why us — headline",
    sortOrder: 31,
    values: {
      de: "Warum m.on?",
      en: "Why Choose m.on?",
      ar: "لماذا m.on؟",
      tr: "Neden m.on?",
    },
  },
  {
    section: "home",
    slot: "why.subline",
    kind: "textarea",
    label: "Why us — subline",
    sortOrder: 32,
    values: {
      de: "Wir kombinieren traditionelles deutsches Handwerk mit modernster digitaler Effizienz.",
      en: "We combine traditional German craftsmanship with state-of-the-art digital efficiency.",
      ar: "نجمع بين الحرفية الألمانية التقليدية والكفاءة الرقمية الحديثة.",
      tr: "Geleneksel Alman ustalığını en modern dijital verimlilikle birleştiriyoruz.",
    },
  },
  {
    section: "home",
    slot: "why.team.title",
    kind: "text",
    label: "Benefit 1 — title",
    sortOrder: 33,
    values: {
      de: "Professionelles Team",
      en: "Professional Team",
      ar: "فريق محترف",
      tr: "Profesyonel Ekip",
    },
  },
  {
    section: "home",
    slot: "why.team.body",
    kind: "textarea",
    label: "Benefit 1 — body",
    sortOrder: 34,
    values: {
      de: "Unser Umzugsteam besteht ausschließlich aus festangestellten, geschulten Fachkräften in Deutschland.",
      en: "Our moving team consists exclusively of employed, trained professionals in Germany.",
      ar: "يتكوّن فريق النقل لدينا حصراً من فنّيين مدرَّبين موظَّفين في ألمانيا.",
      tr: "Taşıma ekibimiz yalnızca Almanya'da kadrolu, eğitimli profesyonellerden oluşur.",
    },
  },
  {
    section: "home",
    slot: "why.punctual.title",
    kind: "text",
    label: "Benefit 2 — title",
    sortOrder: 35,
    values: {
      de: "Schnell & pünktlich",
      en: "Fast & Punctual",
      ar: "سريع ودقيق في المواعيد",
      tr: "Hızlı ve Dakik",
    },
  },
  {
    section: "home",
    slot: "why.punctual.body",
    kind: "textarea",
    label: "Benefit 2 — body",
    sortOrder: 36,
    values: {
      de: "Ob Express-Umzug oder geplante Entrümpelung — wir halten unsere Absprachen auf die Minute genau ein.",
      en: "Whether it's an express move or a scheduled clearance, we stick to our agreements down to the minute.",
      ar: "سواء كان نقلاً عاجلاً أو إخلاءً مجدولاً، نلتزم باتفاقاتنا بدقّة الدقيقة.",
      tr: "İster ekspres taşınma ister planlı boşaltma olsun, anlaşmalarımıza dakikası dakikasına uyarız.",
    },
  },
  {
    section: "home",
    slot: "why.prices.title",
    kind: "text",
    label: "Benefit 3 — title",
    sortOrder: 37,
    values: {
      de: "Faire & transparente Preise",
      en: "Fair & Transparent Prices",
      ar: "أسعار عادلة وشفّافة",
      tr: "Adil ve Şeffaf Fiyatlar",
    },
  },
  {
    section: "home",
    slot: "why.prices.body",
    kind: "textarea",
    label: "Benefit 3 — body",
    sortOrder: 38,
    values: {
      de: "Unser smarter m²-Rechner gibt Ihnen Festpreisgarantien ohne spätere Nachverhandlung.",
      en: "Our smart m² calculator gives you fixed-price guarantees with no later renegotiation.",
      ar: "حاسبة المتر المربّع الذكية لدينا تمنحك ضمانات سعر ثابت دون إعادة تفاوض لاحقة.",
      tr: "Akıllı m² hesaplayıcımız, sonradan pazarlık olmadan sabit fiyat garantisi verir.",
    },
  },
  {
    section: "home",
    slot: "why.insured.title",
    kind: "text",
    label: "Benefit 4 — title",
    sortOrder: 39,
    values: {
      de: "Vollversichert & sicher",
      en: "Fully Insured & Secure",
      ar: "مؤمَّن بالكامل وآمن",
      tr: "Tam Sigortalı ve Güvenli",
    },
  },
  {
    section: "home",
    slot: "why.insured.body",
    kind: "textarea",
    label: "Benefit 4 — body",
    sortOrder: 40,
    values: {
      de: "Falls doch etwas passiert: Jede Immobilie und jeder Transport ist durch unsere Allianz-Haftpflichtversicherung geschützt.",
      en: "If anything happens: every property and every transport is protected by our Allianz liability insurance.",
      ar: "وإن حدث شيء: كل عقار وكل عملية نقل محميّة بتأمين المسؤولية من Allianz.",
      tr: "Bir şey olursa: her mülk ve her nakliye Allianz sorumluluk sigortamızla korunur.",
    },
  },

  // ── How it works ────────────────────────────────────────────────────
  {
    section: "home",
    slot: "how.eyebrow",
    kind: "text",
    label: "How it works — eyebrow",
    sortOrder: 50,
    values: {
      de: "In 3 einfachen Schritten",
      en: "In 3 Easy Steps",
      ar: "في 3 خطوات بسيطة",
      tr: "3 Kolay Adımda",
    },
  },
  {
    section: "home",
    slot: "how.headline",
    kind: "text",
    label: "How it works — headline",
    sortOrder: 51,
    values: {
      de: "So funktioniert es",
      en: "How It Works",
      ar: "كيف يعمل",
      tr: "Nasıl Çalışır",
    },
  },
  {
    section: "home",
    slot: "how.subline",
    kind: "textarea",
    label: "How it works — subline",
    sortOrder: 52,
    values: {
      de: "Unser vollständig digitaler Ablauf spart Ihnen Zeit, Telefonate und lästigen Papierkram.",
      en: "Our fully digital process saves you time, phone calls, and tedious paperwork.",
      ar: "عمليتنا الرقمية بالكامل توفّر عليك الوقت والمكالمات والأوراق المزعجة.",
      tr: "Tamamen dijital sürecimiz size zaman, telefon görüşmesi ve angarya evrak işi kazandırır.",
    },
  },
  {
    section: "home",
    slot: "how.step1.title",
    kind: "text",
    label: "Step 1 — title",
    sortOrder: 53,
    values: {
      de: "Kostenloses Angebot",
      en: "Free Quote",
      ar: "عرض سعر مجاني",
      tr: "Ücretsiz Teklif",
    },
  },
  {
    section: "home",
    slot: "how.step1.body",
    kind: "textarea",
    label: "Step 1 — body",
    sortOrder: 54,
    values: {
      de: "Nutzen Sie unseren m²-Rechner für ein unverbindliches Angebot in Echtzeit.",
      en: "Use our m² calculator for a non-binding offer in real time.",
      ar: "استخدم حاسبة المتر المربّع للحصول على عرض غير مُلزم فوراً.",
      tr: "Gerçek zamanlı, bağlayıcı olmayan teklif için m² hesaplayıcımızı kullanın.",
    },
  },
  {
    section: "home",
    slot: "how.step2.title",
    kind: "text",
    label: "Step 2 — title",
    sortOrder: 55,
    values: {
      de: "Termin buchen",
      en: "Book a Date",
      ar: "احجز موعداً",
      tr: "Tarih Seçin",
    },
  },
  {
    section: "home",
    slot: "how.step2.body",
    kind: "textarea",
    label: "Step 2 — body",
    sortOrder: 56,
    values: {
      de: "Sichern Sie sich Ihren Wunschtermin bequem online oder mit unserem Berater.",
      en: "Secure your preferred date easily online or with our advisor.",
      ar: "احجز موعدك المفضّل بسهولة عبر الإنترنت أو مع مستشارنا.",
      tr: "Tercih ettiğiniz tarihi çevrimiçi ya da danışmanımızla kolayca ayırtın.",
    },
  },
  {
    section: "home",
    slot: "how.step3.title",
    kind: "text",
    label: "Step 3 — title",
    sortOrder: 57,
    values: {
      de: "Umzug & Übergabe",
      en: "Move & Delivery",
      ar: "النقل والتسليم",
      tr: "Taşınma ve Teslim",
    },
  },
  {
    section: "home",
    slot: "how.step3.body",
    kind: "textarea",
    label: "Step 3 — body",
    sortOrder: 58,
    values: {
      de: "Unser Premium-Team erledigt den Rest — pünktlich, sauber und absolut professionell.",
      en: "Our premium team takes care of the rest punctually, cleanly, and absolutely professionally.",
      ar: "فريقنا المتميّز يتولّى الباقي في موعده وبنظافة واحتراف تام.",
      tr: "Premium ekibimiz gerisini dakik, temiz ve son derece profesyonel biçimde halleder.",
    },
  },

  // ── Add-ons ─────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "addons.eyebrow",
    kind: "text",
    label: "Add-ons — eyebrow",
    sortOrder: 60,
    values: {
      de: "Optionale Zusatzleistungen",
      en: "Optional Add-ons",
      ar: "خدمات إضافية اختيارية",
      tr: "İsteğe Bağlı Ek Hizmetler",
    },
  },
  {
    section: "home",
    slot: "addons.headline",
    kind: "text",
    label: "Add-ons — headline",
    sortOrder: 61,
    values: {
      de: "Alles, was Sie für Ihren Umzug brauchen",
      en: "Everything You Need for Your Move",
      ar: "كل ما تحتاجه لعملية نقلك",
      tr: "Taşınmanız İçin Gereken Her Şey",
    },
  },
  {
    section: "home",
    slot: "addons.subline",
    kind: "textarea",
    label: "Add-ons — subline",
    sortOrder: 62,
    values: {
      de: "Erweitern Sie Ihr Basispaket flexibel um professionelle Zusatzleistungen.",
      en: "Flexibly extend your basic package with professional extra services.",
      ar: "وسّع باقتك الأساسية بمرونة بخدمات إضافية احترافية.",
      tr: "Temel paketinizi profesyonel ek hizmetlerle esnekçe genişletin.",
    },
  },
  {
    section: "home",
    slot: "addons.packing.title",
    kind: "text",
    label: "Add-on 1 — title",
    sortOrder: 63,
    values: {
      de: "Packservice & Materialien",
      en: "Packing Service & Materials",
      ar: "خدمة التغليف والمواد",
      tr: "Paketleme Hizmeti ve Malzemeler",
    },
  },
  {
    section: "home",
    slot: "addons.packing.body",
    kind: "textarea",
    label: "Add-on 1 — body",
    sortOrder: 64,
    values: {
      de: "Unser Team packt Ihren gesamten Haushalt am Vortag sicher in Premium-Umzugskartons. Luftpolsterfolie, Matratzenhüllen und Kleiderboxen bringen wir kostenlos mit.",
      en: "Our team packs your entire household safely into premium moving boxes the day before. We bring bubble wrap, mattress covers, and wardrobe boxes free of charge.",
      ar: "يغلّف فريقنا كامل محتويات منزلك بأمان في صناديق نقل ممتازة قبل الموعد بيوم. نُحضر مجاناً الفقاعات الهوائية وأغطية المراتب وصناديق الملابس.",
      tr: "Ekibimiz bir gün önce tüm evinizi güvenle premium taşıma kutularına yerleştirir. Baloncuklu naylon, yatak kılıfı ve gardırop kutularını ücretsiz getiririz.",
    },
  },
  {
    section: "home",
    slot: "addons.packing.price",
    kind: "text",
    label: "Add-on 1 — price line",
    sortOrder: 65,
    values: {
      de: "Preisrichtwert: ab 2,50 € pro Karton inkl. Packservice",
      en: "Price indication: from €2.50 per box including packing service",
      ar: "السعر التقريبي: ابتداءً من 2,50 € للصندوق شاملاً خدمة التغليف",
      tr: "Fiyat göstergesi: paketleme hizmeti dahil kutu başına 2,50 €'dan başlar",
    },
  },
  {
    section: "home",
    slot: "addons.assembly.title",
    kind: "text",
    label: "Add-on 2 — title",
    sortOrder: 66,
    values: {
      de: "Möbelmontage & Küchenaufbau",
      en: "Furniture Assembly & Kitchen Setup",
      ar: "تركيب الأثاث وتجهيز المطبخ",
      tr: "Mobilya Montajı ve Mutfak Kurulumu",
    },
  },
  {
    section: "home",
    slot: "addons.parking.title",
    kind: "text",
    label: "Add-on 3 — title",
    sortOrder: 67,
    values: {
      de: "Halteverbotszone (HVZ) einrichten",
      en: "No-Parking-Zone (HVZ) Setup",
      ar: "تجهيز منطقة حظر الوقوف (HVZ)",
      tr: "Park Yasağı Bölgesi (HVZ) Kurulumu",
    },
  },
  {
    section: "home",
    slot: "addons.storage.title",
    kind: "text",
    label: "Add-on 4 — title",
    sortOrder: 68,
    values: {
      de: "Einlagerung auf Abruf",
      en: "On-Demand Storage",
      ar: "تخزين عند الطلب",
      tr: "Talep Üzerine Depolama",
    },
  },

  // ── Coverage ────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "areas.eyebrow",
    kind: "text",
    label: "Coverage — eyebrow",
    sortOrder: 70,
    values: { de: "Einsatzgebiet", en: "Coverage", ar: "نطاق الخدمة", tr: "Hizmet Alanı" },
  },
  {
    section: "home",
    slot: "areas.headline",
    kind: "text",
    label: "Coverage — headline",
    sortOrder: 71,
    values: {
      de: "Wo wir tätig sind",
      en: "Where We Operate",
      ar: "أين نعمل",
      tr: "Nerelerde Hizmet Veriyoruz",
    },
  },
  {
    section: "home",
    slot: "areas.subline",
    kind: "textarea",
    label: "Coverage — subline",
    sortOrder: 72,
    values: {
      de: "Wir bieten Umzugs- und Reinigungsleistungen in allen großen Metropolregionen an.",
      en: "We offer moving and cleaning services in all major metropolitan regions.",
      ar: "نقدّم خدمات النقل والتنظيف في جميع المناطق الحضرية الكبرى.",
      tr: "Tüm büyük metropol bölgelerinde taşıma ve temizlik hizmeti sunuyoruz.",
    },
  },
  {
    section: "home",
    slot: "areas.cities",
    kind: "textarea",
    label: "Coverage — city list (comma separated)",
    sortOrder: 73,
    values: {
      de: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg, Wandsbek, Altona",
      en: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg, Wandsbek, Altona",
      ar: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg, Wandsbek, Altona",
      tr: "Berlin, München, Hamburg, Köln, Frankfurt am Main, Stuttgart, Düsseldorf, Dortmund, Leipzig, Essen, Bremen, Dresden, Hannover, Nürnberg, Duisburg, Wandsbek, Altona",
    },
  },

  // ── Reviews ─────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "reviews.eyebrow",
    kind: "text",
    label: "Reviews — eyebrow",
    sortOrder: 80,
    values: {
      de: "Kundenstimmen",
      en: "Customer Feedback",
      ar: "آراء العملاء",
      tr: "Müşteri Geri Bildirimi",
    },
  },
  {
    section: "home",
    slot: "reviews.headline",
    kind: "text",
    label: "Reviews — headline",
    sortOrder: 81,
    values: {
      de: "Was unsere Kunden sagen",
      en: "What Our Customers Say",
      ar: "ماذا يقول عملاؤنا",
      tr: "Müşterilerimiz Ne Diyor",
    },
  },
  {
    section: "home",
    slot: "reviews.subline",
    kind: "textarea",
    label: "Reviews — subline",
    sortOrder: 82,
    values: {
      de: "Über 10.000 erfolgreiche Umzüge in ganz Deutschland.",
      en: "Over 10,000 successful moves completed across Germany.",
      ar: "أكثر من 10,000 عملية نقل ناجحة في جميع أنحاء ألمانيا.",
      tr: "Almanya genelinde 10.000'den fazla başarılı taşınma.",
    },
  },

  {
    section: "home",
    slot: "reviews.t1.quote",
    kind: "textarea",
    label: "Testimonial 1 — quote",
    sortOrder: 85,
    values: {
      de: "„Der m²-Rechner hat mir sofort einen fairen Festpreis berechnet. Das Team stand am nächsten Tag super pünktlich vor der Tür. Extrem vorsichtige Handhabung meiner Designermöbel!“",
      en: "\"The m² calculator gave me a fair fixed price immediately. The team was at my door the next day, right on time. Extremely careful handling of my designer furniture!\"",
      ar: "«حاسبة المتر المربّع أعطتني سعراً ثابتاً عادلاً فوراً. وصل الفريق في اليوم التالي في الموعد تماماً. تعامل شديد الحرص مع أثاثي المصمَّم!»",
      tr: "\"m² hesaplayıcı bana anında adil bir sabit fiyat verdi. Ekip ertesi gün tam zamanında kapıdaydı. Tasarım mobilyalarıma karşı son derece özenliydiler!\"",
    },
  },
  {
    section: "home",
    slot: "reviews.t1.name",
    kind: "text",
    label: "Testimonial 1 — name",
    sortOrder: 86,
    values: {
      de: "Maximilian S. aus München",
      en: "Maximilian S. from Munich",
      ar: "ماكسيميليان س. من ميونخ",
      tr: "Münih'ten Maximilian S.",
    },
  },
  {
    section: "home",
    slot: "reviews.t1.service",
    kind: "text",
    label: "Testimonial 1 — service",
    sortOrder: 87,
    values: {
      de: "Umzug (75 m²) + Entrümpelung",
      en: "Move (75m²) + Clearance",
      ar: "نقل (75 م²) + إخلاء",
      tr: "Taşınma (75m²) + Boşaltma",
    },
  },
  {
    section: "home",
    slot: "reviews.t2.quote",
    kind: "textarea",
    label: "Testimonial 2 — quote",
    sortOrder: 88,
    values: {
      de: "„Überragender Service! Küche abgebaut, transportiert und in der neuen Wohnung perfekt wieder aufgebaut. Dazu die Endreinigung mit Übergabegarantie gebucht — stressfreier geht es nicht.“",
      en: "\"Outstanding service! Kitchen dismantled, transported and reassembled perfectly in the new flat. We also booked the final cleaning with handover guarantee — it could not have been less stressful.\"",
      ar: "«خدمة ممتازة! فُكّ المطبخ ونُقل وأُعيد تركيبه بإتقان في الشقة الجديدة. وحجزنا أيضاً التنظيف النهائي مع ضمان التسليم — لا يمكن أن يكون الأمر أسهل.»",
      tr: "\"Olağanüstü hizmet! Mutfak söküldü, taşındı ve yeni dairede kusursuz şekilde yeniden kuruldu. Ayrıca teslim garantili son temizliği de aldık — daha stressiz olamazdı.\"",
    },
  },
  {
    section: "home",
    slot: "reviews.t2.name",
    kind: "text",
    label: "Testimonial 2 — name",
    sortOrder: 89,
    values: {
      de: "Dr. Julia Wagner aus Frankfurt",
      en: "Dr. Julia Wagner from Frankfurt",
      ar: "د. يوليا فاغنر من فرانكفورت",
      tr: "Frankfurt'tan Dr. Julia Wagner",
    },
  },
  {
    section: "home",
    slot: "reviews.t2.service",
    kind: "text",
    label: "Testimonial 2 — service",
    sortOrder: 90,
    values: {
      de: "Premium-Umzug + Küchenmontage",
      en: "Premium Move + Kitchen Assembly",
      ar: "نقل متميّز + تركيب مطبخ",
      tr: "Premium Taşınma + Mutfak Montajı",
    },
  },
  {
    section: "home",
    slot: "reviews.t3.quote",
    kind: "textarea",
    label: "Testimonial 3 — quote",
    sortOrder: 91,
    values: {
      de: "„Besonders die besenreine Haushaltsauflösung meiner Großeltern lief absolut geräuschlos und diskret. Extrem faires m²-Angebot und keine unliebsamen Überraschungen bei der Rechnung.“",
      en: "\"The broom-clean clearance of my grandparents' home in particular was completely quiet and discreet. An extremely fair m² offer and no unwelcome surprises on the invoice.\"",
      ar: "«إخلاء منزل جدّيّ تحديداً جرى بهدوء تام وتكتّم. عرض عادل جداً بالمتر المربّع وبلا مفاجآت مزعجة في الفاتورة.»",
      tr: "\"Özellikle büyükannemlerin evinin süpürge temizliğiyle boşaltılması tamamen sessiz ve nazikti. Son derece adil bir m² teklifi ve faturada hoş olmayan sürpriz yok.\"",
    },
  },
  {
    section: "home",
    slot: "reviews.t3.name",
    kind: "text",
    label: "Testimonial 3 — name",
    sortOrder: 92,
    values: {
      de: "Annette K. aus Berlin",
      en: "Annette K. from Berlin",
      ar: "أنيت ك. من برلين",
      tr: "Berlin'den Annette K.",
    },
  },
  {
    section: "home",
    slot: "reviews.t3.service",
    kind: "text",
    label: "Testimonial 3 — service",
    sortOrder: 93,
    values: {
      de: "Haushaltsauflösung (120 m²)",
      en: "Household Clearance (120m²)",
      ar: "إخلاء منزل (120 م²)",
      tr: "Ev Boşaltma (120m²)",
    },
  },

  // ── FAQ ─────────────────────────────────────────────────────────────
  {
    section: "home",
    slot: "faq.eyebrow",
    kind: "text",
    label: "FAQ — eyebrow",
    sortOrder: 90,
    values: {
      de: "Häufige Fragen",
      en: "Frequently Asked Questions",
      ar: "الأسئلة الشائعة",
      tr: "Sık Sorulan Sorular",
    },
  },
  {
    section: "home",
    slot: "faq.headline",
    kind: "text",
    label: "FAQ — headline",
    sortOrder: 91,
    values: {
      de: "Häufig gestellte Fragen",
      en: "Frequently Asked Questions",
      ar: "الأسئلة الأكثر شيوعاً",
      tr: "Sık Sorulan Sorular",
    },
  },
  {
    section: "home",
    slot: "faq.subline",
    kind: "textarea",
    label: "FAQ — subline",
    sortOrder: 92,
    values: {
      de: "Alles Wichtige zu Abrechnung, Versicherung und unseren Abläufen.",
      en: "Everything you need to know about billing, insurance, and our processes.",
      ar: "كل ما تحتاج معرفته عن الفوترة والتأمين وإجراءاتنا.",
      tr: "Faturalandırma, sigorta ve süreçlerimiz hakkında bilmeniz gereken her şey.",
    },
  },

  // ── Final call to action ────────────────────────────────────────────
  {
    section: "home",
    slot: "cta.eyebrow",
    kind: "text",
    label: "Final CTA — eyebrow",
    sortOrder: 100,
    values: {
      de: "Schnell & unverbindlich",
      en: "Fast & Non-binding",
      ar: "سريع وغير مُلزم",
      tr: "Hızlı ve Bağlayıcı Değil",
    },
  },
  {
    section: "home",
    slot: "cta.headline",
    kind: "text",
    label: "Final CTA — headline",
    sortOrder: 101,
    values: {
      de: "Bereit für den Umzug?",
      en: "Ready to Move?",
      ar: "جاهز للانتقال؟",
      tr: "Taşınmaya Hazır mısınız?",
    },
  },
  {
    section: "home",
    slot: "cta.body",
    kind: "textarea",
    label: "Final CTA — body",
    sortOrder: 102,
    values: {
      de: "Berechnen Sie Ihren garantierten Festpreis in unter 2 Minuten. Völlig kostenlos und ohne Registrierung.",
      en: "Calculate your guaranteed fixed price in under 2 minutes. Completely free and no registration required.",
      ar: "احسب سعرك الثابت المضمون في أقل من دقيقتين. مجاناً تماماً وبدون تسجيل.",
      tr: "Garantili sabit fiyatınızı 2 dakikadan kısa sürede hesaplayın. Tamamen ücretsiz, kayıt gerekmez.",
    },
  },
  {
    section: "home",
    slot: "cta.placeholder",
    kind: "text",
    label: "Final CTA — input placeholder",
    sortOrder: 103,
    values: {
      de: "Wohnfläche eingeben (z. B. 65 m²)...",
      en: "Enter living area (e.g. 65 m²)...",
      ar: "أدخل المساحة السكنية (مثلاً 65 م²)...",
      tr: "Yaşam alanını girin (örn. 65 m²)...",
    },
  },
  {
    section: "home",
    slot: "cta.button",
    kind: "text",
    label: "Final CTA — button",
    sortOrder: 104,
    values: {
      de: "Preis berechnen",
      en: "Calculate Price",
      ar: "احسب السعر",
      tr: "Fiyat Hesapla",
    },
  },
  {
    section: "home",
    slot: "cta.trust1",
    kind: "text",
    label: "Final CTA — trust 1",
    sortOrder: 105,
    values: {
      de: "Keine Anzahlung nötig",
      en: "No Deposit Required",
      ar: "لا حاجة لدفعة مقدّمة",
      tr: "Kapora Gerekmez",
    },
  },
  {
    section: "home",
    slot: "cta.trust2",
    kind: "text",
    label: "Final CTA — trust 2",
    sortOrder: 106,
    values: {
      de: "Festpreisgarantie",
      en: "Fixed-Price Guarantee",
      ar: "ضمان السعر الثابت",
      tr: "Sabit Fiyat Garantisi",
    },
  },
  {
    section: "home",
    slot: "cta.trust3",
    kind: "text",
    label: "Final CTA — trust 3",
    sortOrder: 107,
    values: {
      de: "Deutscher Qualitätsstandard",
      en: "German Quality Standard",
      ar: "معيار الجودة الألماني",
      tr: "Alman Kalite Standardı",
    },
  },

  // ── Footer ──────────────────────────────────────────────────────────
  {
    section: "footer",
    slot: "tagline",
    kind: "textarea",
    label: "Footer — tagline",
    sortOrder: 1,
    values: {
      de: "Ihr digitaler Partner für Umzug, Reinigung und Entrümpelung in ganz Deutschland. Schnell, transparent und zuverlässig.",
      en: "Your digital partner for moving, cleaning, and clearance across Germany. Fast, transparent, and reliable.",
      ar: "شريكك الرقمي للنقل والتنظيف والإخلاء في جميع أنحاء ألمانيا. سريع وشفّاف وموثوق.",
      tr: "Almanya genelinde taşınma, temizlik ve boşaltma için dijital ortağınız. Hızlı, şeffaf ve güvenilir.",
    },
  },
  {
    section: "footer",
    slot: "address",
    kind: "textarea",
    label: "Footer — address",
    sortOrder: 2,
    values: {
      de: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      en: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      ar: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
      tr: "m.on GmbH, Kurfürstendamm 212, 10719 Berlin",
    },
  },
  {
    section: "footer",
    slot: "rights",
    kind: "text",
    label: "Footer — rights",
    sortOrder: 3,
    values: {
      de: "Alle Rechte vorbehalten.",
      en: "All rights reserved.",
      ar: "جميع الحقوق محفوظة.",
      tr: "Tüm hakları saklıdır.",
    },
  },
  {
    section: "home",
    slot: "services.learnMore",
    kind: "text",
    label: "Service cards — link label",
    sortOrder: 25,
    values: { de: "Mehr erfahren", en: "Learn More", ar: "اعرف المزيد", tr: "Daha Fazla" },
  },

  // ── Footer ──────────────────────────────────────────────────────────
  {
    section: "footer",
    slot: "brand",
    kind: "text",
    label: "Footer — legal name",
    sortOrder: 0,
    values: {
      de: "m.on GmbH",
      en: "m.on GmbH",
      ar: "m.on GmbH",
      tr: "m.on GmbH",
    },
  },
  {
    section: "footer",
    slot: "servicesTitle",
    kind: "text",
    label: "Footer — services column heading",
    sortOrder: 10,
    values: { de: "Leistungen", en: "Services", ar: "الخدمات", tr: "Hizmetler" },
  },
  {
    section: "footer",
    slot: "link.residential",
    kind: "text",
    label: "Footer link — residential move",
    sortOrder: 11,
    values: { de: "Privatumzug", en: "Residential Move", ar: "نقل سكني", tr: "Konut Taşıma" },
  },
  {
    section: "footer",
    slot: "link.corporate",
    kind: "text",
    label: "Footer link — corporate move",
    sortOrder: 12,
    values: { de: "Firmenumzug", en: "Corporate Move", ar: "نقل الشركات", tr: "Kurumsal Taşıma" },
  },
  {
    section: "footer",
    slot: "link.clearance",
    kind: "text",
    label: "Footer link — clearance",
    sortOrder: 13,
    values: {
      de: "Haushaltsauflösung",
      en: "Household Clearance",
      ar: "إخلاء المنازل",
      tr: "Ev Boşaltma",
    },
  },
  {
    section: "footer",
    slot: "link.senior",
    kind: "text",
    label: "Footer link — senior move",
    sortOrder: 14,
    values: { de: "Seniorenumzug", en: "Senior Move", ar: "نقل كبار السن", tr: "Yaşlı Taşıma" },
  },
  {
    section: "footer",
    slot: "link.cleaning",
    kind: "text",
    label: "Footer link — final cleaning",
    sortOrder: 15,
    values: { de: "Endreinigung", en: "Final Cleaning", ar: "التنظيف النهائي", tr: "Son Temizlik" },
  },
  {
    section: "footer",
    slot: "link.storage",
    kind: "text",
    label: "Footer link — storage",
    sortOrder: 16,
    values: { de: "Möbeleinlagerung", en: "Furniture Storage", ar: "تخزين الأثاث", tr: "Mobilya Depolama" },
  },
  {
    section: "footer",
    slot: "contactTitle",
    kind: "text",
    label: "Footer — contact column heading",
    sortOrder: 20,
    values: {
      de: "Kontakt & Support",
      en: "Contact & Support",
      ar: "الاتصال والدعم",
      tr: "İletişim ve Destek",
    },
  },
  {
    section: "footer",
    slot: "phone",
    kind: "text",
    label: "Footer — phone",
    sortOrder: 21,
    values: {
      de: "0800 123 456 78",
      en: "0800 123 456 78",
      ar: "0800 123 456 78",
      tr: "0800 123 456 78",
    },
  },
  {
    section: "footer",
    slot: "email",
    kind: "text",
    label: "Footer — email",
    sortOrder: 22,
    values: {
      de: "support@moveongo.de",
      en: "support@moveongo.de",
      ar: "support@moveongo.de",
      tr: "support@moveongo.de",
    },
  },
  {
    section: "footer",
    slot: "legal.imprint",
    kind: "text",
    label: "Footer legal — imprint",
    sortOrder: 30,
    values: { de: "Impressum", en: "Imprint", ar: "بيانات الناشر", tr: "Künye" },
  },
  {
    section: "footer",
    slot: "legal.privacy",
    kind: "text",
    label: "Footer legal — privacy",
    sortOrder: 31,
    values: { de: "Datenschutz", en: "Privacy Policy", ar: "سياسة الخصوصية", tr: "Gizlilik" },
  },
  {
    section: "footer",
    slot: "legal.terms",
    kind: "text",
    label: "Footer legal — terms",
    sortOrder: 32,
    values: { de: "AGB", en: "Terms", ar: "الشروط والأحكام", tr: "Şartlar" },
  },
  {
    section: "footer",
    slot: "legal.cookies",
    kind: "text",
    label: "Footer legal — cookies",
    sortOrder: 33,
    values: { de: "Cookie-Richtlinie", en: "Cookie Policy", ar: "سياسة الكوكيز", tr: "Çerez Politikası" },
  },
  {
    section: "footer",
    slot: "social.instagram",
    kind: "text",
    label: "Footer social — Instagram URL",
    sortOrder: 40,
    values: {
      de: "https://instagram.com/mon",
      en: "https://instagram.com/mon",
      ar: "https://instagram.com/mon",
      tr: "https://instagram.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.x",
    kind: "text",
    label: "Footer social — X URL",
    sortOrder: 41,
    values: {
      de: "https://x.com/mon",
      en: "https://x.com/mon",
      ar: "https://x.com/mon",
      tr: "https://x.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.facebook",
    kind: "text",
    label: "Footer social — Facebook URL",
    sortOrder: 42,
    values: {
      de: "https://facebook.com/mon",
      en: "https://facebook.com/mon",
      ar: "https://facebook.com/mon",
      tr: "https://facebook.com/mon",
    },
  },
  {
    section: "footer",
    slot: "social.youtube",
    kind: "text",
    label: "Footer social — YouTube URL",
    sortOrder: 43,
    values: {
      de: "https://youtube.com/@mon",
      en: "https://youtube.com/@mon",
      ar: "https://youtube.com/@mon",
      tr: "https://youtube.com/@mon",
    },
  },
];
