/**
 * GENERATED by apps/web/scripts/build-germany-map.mjs — edit the script, not
 * this file, and rerun it so the pins stay projected like the drawing.
 *
 * Where each city sits on /images/home/germany-map.svg, as the pin's centre
 * in percent of the map's width and height (equirectangular, x scaled by
 * cos 51.17°, fitted to 532x572).
 */
export type MapCity = {
  name: string;
  /** Shorter name printed on the map, where the frame uses one. */
  label?: string;
  aliases?: readonly string[];
  x: number;
  y: number;
};

export const GERMANY_MAP = { src: "/images/home/germany-map.svg", width: 532, height: 572 } as const;

export const MAP_CITIES: readonly MapCity[] = [
  { name: "Berlin", x: 72.6, y: 34.7 },
  { name: "München", aliases: ["Munich", "Muenchen", "Münih"], x: 58.7, y: 84.3 },
  { name: "Hamburg", x: 46.6, y: 23.1 },
  { name: "Köln", aliases: ["Cologne", "Koeln", "Kolonya"], x: 23.5, y: 52.6 },
  { name: "Frankfurt am Main", label: "Frankfurt", aliases: ["Frankfurt"], x: 36.6, y: 61.9 },
  { name: "Stuttgart", x: 40.4, y: 77 },
  { name: "Düsseldorf", aliases: ["Duesseldorf", "Dusseldorf"], x: 22.1, y: 49.3 },
  { name: "Dortmund", x: 27.4, y: 46.1 },
  { name: "Leipzig", x: 64.8, y: 48.1 },
  { name: "Essen", x: 23.9, y: 46.7 },
  { name: "Bremen", x: 37.5, y: 28.4 },
  { name: "Dresden", x: 75.2, y: 51.3 },
  { name: "Hannover", aliases: ["Hanover"], x: 44.6, y: 36.3 },
  { name: "Nürnberg", aliases: ["Nuremberg", "Nuernberg"], x: 54.9, y: 69.4 },
  { name: "Duisburg", x: 22, y: 47 },
];
